location: [642202.50, 5163856.06]
crs: 25832
dem: data/dem100m.tif
price: 45 #ct/kWh
area_optim:

consumption:
    consumption_tbl: 'data/power_consumption.xlsx'

optimization:
    optimize_params: true
    optim_dir: data/optim
    optim_file: 'data/optim/optim_result_2025_02_22_1443.csv'

#20000 / 400
#20000 / 440
panels:
  south: 
    area: 0
    offset: 7
    slope: 15
    aspect: 270
    efficiency: [0.15, 0.2]
    system_loss: [0.75, 0.85]

FeatureSolarRadiation:
    unique_id_field: ID
    time_zone: UTC
    start_date_time: "1/1/2024"
    end_date_time: "12/31/2024"
    interval_unit: DAY
    interval: 1
    diffuse_model_type: UNIFORM_SKY
    diffuse_proportion: 0.3
    transmittivity: 0.5

logging:
    version: 1
    disable_existing_loggers: false
    formatters: 
        standard:
            format: "%(asctime)s - %(levelname)s - %(filename)s: %(message)s"
            datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: standard
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: standard
            level: DEBUG
            filename: ./data/log.log #path where to store the log file
            mode: a
            encoding: utf-8
            maxBytes: 50000000 #50MB
            backupCount: 4
    loggers:
        root:
            handlers: [console, file]
            level: DEBUG
